name: Build Android APK with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    # --- تنها تغییر اینجاست ---
    runs-on: ubuntu-22.04  # از نسخه پایدار 22.04 استفاده می‌کنیم

    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set ownership for workspace
        # این دستور برای حل مشکلات احتمالی دسترسی در محیط داکر است
        run: sudo chown -R 1001:1001 .

      - name: Build with Buildozer
        run: buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kos_VPN-APK
          path: bin/*.apk
          if-no-files-found: error
