name: Build Android APK with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set ownership for workspace
        run: sudo chown -R $(whoami) .

      - name: Build with Buildozer
        run: buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kos_VPN-APK
          path: bin/*.apk
          if-no-files-found: error
